### ISSUE TITLE
Importing library error

### ISSUE THREAD

**Issue by nikosT** [cgalleguillosm/accasim#8]
After successfully installed accasim in python3.5 using the pip tool, when trying the below command via the Python shell:
`from accasim.base.simulator_class import hpc_simulator`

I get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'hpc_simulator'`

**Comment by cgalleguillosm** [comment]
Hi,
That isn't an importing error. 
Classes were renamed, you can check the updated version in the following paper.

https://arxiv.org/abs/1806.06728

We expect to add new and more examples as soon as possible.
Best.


```
from accasim.base.simulator_class import Simulator
from accasim.base.scheduler_class import FirstInFirstOut
from accasim.base.allocator_class import FirstFit

workload = 'your workload filepath in swf'
sys_config = 'your system config filepath'

allocator = FirstFit()
dispatcher = FirstInFirstOut(allocator)
    
simulator = Simulator(workload, sys_config, dispatcher)
simulator.start_simulation()
```
